README.md
GitHub's Markdown rendering puts a border line below the headline.
Unfortunately, that stroke through the "then" badge. Raising it above
the build status or same height should fix this.
=> Readme: fix line-through on github

README.md
GitHub's Markdown rendering puts a border line below the headline.
Unfortunately, that stroke through the "then" badge. Raising it above
the build status or same height should fix this.
Moved bird logo down into the "Features" section for same reason.
Minor: Remove "Features:" colon to fit other headlines' style.
Minor: Replace U+0303 combining tilde with HTML asymp.
=> Readme: fix line-through on github (including Features section)

src/constants.js
I'm not sure if 'unhanded' means something and this actually was correct. I would expect it to not be handled, e.g. 'unhandled'.
=> Correct spelling of 'unhandled'

src/captured_trace.js
Motivating example
If a chain of traces is made that looks like this
c -> b -> a
then you add `d` and `e` to form two chains
d -> c -> b -> a,
e -> c -> b -> a
decycling from d will not update the length of e (and lead to a crash when `e.decycle()` is called later)
This patch fixes that by not relying on that length for anything else
except as a heuristic whether to decycle or not
=> Fix captured trace length issue when decycling

API.md
=> added documentation about non-arrays passed to .spread

README.md
npm.org [apparently](https://github.com/npm/newww/issues/604) follows a Markdown standard that requires a whitespace character follow the #'s to make it a header.
This should make the README display correctly on the [bluebird](https://www.npmjs.com/package/bluebird) package page.
=> Add spaces after # headers in README.md

API.md
I just ran into a bug where my clients were being destroyed.  I pinned it down to this line of code.  According to:
https://github.com/brianc/node-postgres/wiki/pg#parameters
You should only pass a truthy value if you want the client to be destroyed and removed from the connection pool - which is not normally the case.  Even if it was the example's intent, you should simply pass in 'true' instead of the client, because it is misleading to the reader in what is actually going on.
=> connection pool 'close' method

API.md
=> Clarify that console methods need to be bound for use with tap

API.md
1. Rewording the `concurrency` limit option documentation
2. Updating the `concurrency` link in `filter` to point to the `concurrency` limit section in `map`, instead of `map` itself.
=> Rewording the `concurrency` limit option doc

README.md
Its short and inviting and right at the beginning to make it harder to miss.
=> Add short support channel summary in README

docs/_layouts/default.html
It was linking to `/bluebird/`, but the new site needs it to link to `/`.
=> Fix "home" link in jekyll default layout

docs/docs/new-in-bluebird-3.md
Strictly speaking bumping to 4.0.0 will adhere more strongly to semver, but we've broken semver before in 2.x when the breakage was unlikely to affect anyone - and this breakage would only affect users who started relying on the new `each` behavior in the past 10 hours.
Thoughts?
=> Add notice about 3.0.1

docs/docs/api/finally.md
Looks like a broken link from how the previous version of the docs were structured
=> docs: Fix "resource management" link

docs/docs/why-promises.md
- Fixed broken link to API docs on promisification.
- Made JavaScript examples more consistent (semicolons, spacing, used existing Gecko syntax for illustrative example).
- Tightened up prose with minor punctuation changes and rewording.
=> Why promises page: copy changes, fixed link to promisification

docs/docs/api/promise.coroutine.addyieldhandler.md
The docs make use of `defer.callback`, but from running the code and looking at the source code for `Promise.defer` it is apparent that `Promise.defer().callback` is undefined. Instead, use `Promise.fromCallback()`.
=> Docs: use Promise.fromCallback instead of Promise.defer().callback

docs/docs/api/promise.reduce.md
The following code demonstrates the behavior I've documented:
```
var Promise = require('bluebird');
Promise.resolve(['one']).reduce(function(a, n, i, l) {
console.log('Arguments are:', a, n, i, l);
return a + n;
}).then(function(a) {
console.log('Result is:', a);
});
```
It logs:
```
Result is: one
```
=> Fix `reduce` docs: omitted initialValue, iterable of length == 1

docs/_layouts/default.html
Some documentation sites include their own library in the source code so that users can use the debug console as a playground. One example is lodash (https://lodash.com/docs). It makes it a lot easier to quickly test something out. Not a big deal though.
=> Include bluebird in bluebirdjs.com

tools/utils.js
"npm install" on windows failed with unhandled rejection error, which was caused by os specific line separator used for parsing source files.
=> Fixed build on windows

docs/css/main.css
Makes documentation pages visually a bit more pleasing. I didn't succeed to get jekyll running so didn't actually test this locally.
=> Add padding to the bottom of pages

.travis.yml
* Set testing against environments that matter today - NodeJS 0.10, 0.12, 4.x and 5.x
* Moved the same environment settings into their own section
* Added support for the new Travis CI containment mode: `sudo: false`
=> Travis script updates

src/util.js
This is the same PR as #769 but on the current state of the repository because I didn't manage to rebase my previous commit.
Document unreachable code purpose since it's triggering "unreachable code after return statement" warning in Firefox when browserify-ied.
cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1151931
cf. http://stackoverflow.com/questions/24987896/how-does-bluebirds-util-tofastproperties-function-make-an-objects-properties
Note: The text of the comment is a copy of Benjamin Gruenbaum's original comment.
=> Document unreachable code purpose

docs/Gemfile
Oddly, on my Mac OS X system when I run a `bundle install` it does not install **redcarpet** or **pygments**. These are normally installed as dependencies of **jekyll** under the windows platform. This commit fixes the following errors when running `jekyll serve`:
Configuration file: /Users/suki/source/bluebird/docs/_config.yml
/Users/suki/source/bluebird/docs/_plugins/plugin.rb:1:in `require': cannot load such file -- redcarpet (LoadError)
from /Users/suki/source/bluebird/docs/_plugins/plugin.rb:1:in `<top (required)>'
Configuration file: /Users/suki/source/bluebird/docs/_config.yml
/Users/suki/source/bluebird/docs/_plugins/plugin.rb:2:in `require': cannot load such file -- pygments (LoadError)
from /Users/suki/source/bluebird/docs/_plugins/plugin.rb:2:in `<top (required)>'
=> Add redcarpet and pygments to Gemfile

docs/docs/api/promise.using.md, docs/docs/api/resource-management.md
Some of the docs involving `Promise.using` were slightly mangled when migrating documentation from 2.x. This fixes #874.
=> Fix documentation for Promise.using

docs/docs/coming-from-other-libraries.md
The example is written in Promise.mapSeries, not Promise.each
=> Fix a typo

docs/docs/api/promise.fromcallback.md
Looking into the source, it doesn't seem like `fromCallback` will accept boolean as second argument.
=> Fix fromCallback example in doc

docs/docs/api/promise.promisify.md
Fixed name of wrong argument in documentation
=> Update promise.promisify.md to fix argument name

docs/docs/anti-patterns.md, docs/docs/api/new-promise.md
Supercedes #901. As mentioned there I still think it likely makes sense to consolidate by linking to the website from https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns instead of duplicating the content there.
=> Fix links to explicit construction anti-pattern.

docs/docs/api/promise.longstacktraces.md
In response to #961 I've added a deprecation notice to the `Promise.longStackTraces` page for anyone who lands there in future.
=> Docs: Added deprecation notice to Promise.longStackTraces

docs/docs/api/promise.onpossiblyunhandledrejection.md, docs/docs/api/promise.onunhandledrejectionhandled.md
It appears that the previously-relative "global rejection events" links on the `Promise.onPossiblyUnhandledRejection` and `Promise.onUnhandledRejectionHandled` pages were overlooked when the API documentation was split into separate pages in 94fd4fe6.  This PR fixes the links to point to the correct page.
Best,
Kevin
=> doc: Fix the "global rejection events" links

docs/docs/deprecated-apis.md
The URL value for the "Progress Migration" link referenced a nonexistent page (http://bluebirdjs.com/docs/API.md#progression-migration).
=> Update progress migration link URL

docs/docs/api/finally.md
When the handler function passed to `.finally` throws an exception or returns a promise which is later rejected, the promise returned by `.finally` is rejected with the exception or rejected value.
Although this behavior does not appear to be currently documented, it has been in place since at least 0.7.10.  It is also specified in both Ron Buckton's[1] and Domenic Denicola's[2] proposals and present in all of the implementations I checked[3][4][5][6].  So I assume it is safe to document as part of the API.
This PR does just that.
Thanks for considering,
Kevin
1.  https://gist.github.com/rbuckton/66918c8491aa335b003c
2.  https://github.com/domenic/promises-unwrapping/issues/18
3.  https://github.com/cujojs/when/blob/3.7.7/lib/decorators/flow.js#L72
4. …
=> doc: Document when .finally handler returns a promise or throws

docs/docs/api/catch.md
Fix typo and made `ReferenceError` comment more clear.
=> Fix defined/undefined typo

.gitignore, src/generators.js, test/mocha/generator.js
This patches coroutines to continue running after cancellation. There is no way to ensure that they're only running their finally blocks unless the generator iterator supports `.return`, so they could be running a catch block instead.
Might need review / improvements, as well as test on Firefox, and a test of long stack traces.
~~edit: WIP, fixing some final bugs.~~ done
=> Continue coroutine execution of finally blocks when cancelled

docs/docs/api/promiseinspection.md
`PromiseInspection.pending()` does not exist, should be `PromiseInspection.isPending()`
=> Fix typo in PromiseInspection API documentation.

tools/build.js
getOptionalRequireCode() in build.js may not sort the modules correctly. It uses Array.sort(comparator) to sort them. The idea of the code is to move the modules that have some dependencies towards the end. Unfortunately, the comparator function used for sorting is not consistent. Let's assume that modules D1 and D2 have dependencies and modules N1 and N2 do not have dependencies (listed in optionalModuleRequireMap) then the current comparator returns the following inconsistent values:
comparator(D1, D2) == 1; comparator(D2, D1) === 1;
comparator(N1, N2) == -1; comparator(N2, N1) === -1;
It should be comparator(X,Y) > 0 if and only if comparator(Y,X) < 0 for a consistent comparator.
The resulting order is not defined when an inconsistent comparator is passed to Array.sort(). It is a pure …
=> Comparator used by getOptionalRequireCode() should be consistent.

docs/docs/api/promise.map.md
The serial version of `.map()` isn’t `.each()`, it’s `.mapSeries()` – i.e., if you want to replace a piece of code that doesn’t fail when certain promises in an array fail but you want to maintain the order of promise execution, you should use `.mapSeries()`.
e.g.,
```
Promise.map(inspections, ((inspection) -> return inspection().reflect()), {concurrency: 1})
.then (inspection) ->
console.log "\nResults:\n"
inspection
.each (inspection) ->
if inspection.isFulfilled()
console.log "  ✅  #{inspection.value()}"
else
console.log "  ❌  #{inspection.reason().message}"
```
In the above code, replace .map() with .mapSeries() and you will get the desired effect. Replace it with .each(), as previously suggested and you won’t.
Also removed the broken sentence "This makes sense because the order of …
=> Replaced Promise.each with Promise.mapSeries

docs/docs/warning-explanations.md
Turns out this broke the link actually. 😅  I didn't realize that redcarpet strips everything after an unacceptable character.
=> Revert "Fix anchor link on warning explanations"

docs/docs/api/deferred-migration.md
The current link for `the deprecated API docs` is http://bluebirdjs.com/bluebird/web/docs/deprecated_apis.html#promise-resolution
which is 404.
I believe the correct link is to http://bluebirdjs.com/docs/deprecated-apis.html#promise-resolution
=> Fix 404 link in deferred-migration.md

docs/docs/api/isfulfilled.md, docs/docs/api/isrejected.md
Is there a reason *promise* is marked up as code here? It's not in other places like [`.reason`](https://github.com/petkaantonov/bluebird/blob/c1604826ab17b9804f2c102958af01d1b782ce9a/docs/docs/api/reason.md), [`.value`](https://github.com/petkaantonov/bluebird/blob/c1604826ab17b9804f2c102958af01d1b782ce9a/docs/docs/api/value.md).
=> Eliminate excess formatting from isFulfilled()|isRejected() docs

docs/docs/api-reference.md, docs/docs/api/promise.getnewlibrarycopy.md, src/promise.js, test/mocha/getNewLibraryCopy.js
This PR is intended as a basis for discussion, rather than "merge me now!"
It feels to me that in many cases module authors should be encouraged to use their own instance of bluebird, rather than the "global" bluebird retrieved by `require('bluebird')`. Here are some examples of where this is the case:
1. Module modifies/shims Bluebird in some way e.g. [cls-bluebird](https://www.npmjs.com/package/cls-bluebird), [bluebird-extra](https://www.npmjs.com/package/bluebird-extra). The host app or other modules may not expect these modifications and it may break them. In the case of [cls-bluebird](https://www.npmjs.com/package/cls-bluebird), it reduces performance of bluebird globally.
2. Bluebird constructor is altered by using static methods/properties of Bluebird constructor. e.g. I am writing …
=> Static method to create separate instance of Bluebird

docs/docs/api/promise.getnewlibrarycopy.md
This PR fixes a typo in the docs for `Promise.getNewLibraryCopy`. Sorry, my mistake!
=> Fix typo in docs for `Promise.getNewLibraryCopy`

tools/ast_passes.js
`expr.operator === "-"` is repeated. Was it meant to be something else, or can it be removed?
=> Repeated subexpression in ast_passes.js

docs/_layouts/default.html
I personally find the API docs very useful, and I think most people who come to bluebird will too.. it would be nice to have a link for it in the top bar :)
=> add api reference to the top bar

docs/docs/coming-from-other-languages.md
The then type signature should have (a -> (Either (Promise b) b)) instead of just a -> (Either (Promise b) b). The old type signature of this function is equivalent to:
then :: Promise a -> (a -> ((Either (Promise b) b) -> Promise b))
Which isn't quite right. The type signature for (>>=) reflects my change.
Also the final b was capitalized, which is wrong since Haskell uses lower cased letters as type variables, not upper cased ones.
=> Fix Haskell's then's type

docs/docs/api/error.md
Original link was (I think): `[long stack traces](/docs/features.html#long-stack-traces)`
http://bluebirdjs.com/docs/features.html#long-stack-traces
But that doesn't explain anymore how to turn the feature on...
Or perhaps link to: http://bluebirdjs.com/docs/install.html#browserify-and-webpack
=> docus: fixed link error.md -> features/long-stack-traces

src/promise.js
I spent a while debugging an error in my promise heavy API and a lit of that time could have been mitigated if I had an error that told me that the error occurred as a `.catch` statement predicate. If the error prefix needs to be moved somewhere else, just let me know.
=> Making .catch Error Predicates More Descriptive

docs/docs/api/deferred-migration.md
For some reason `/docs/deprecated-apis.html` becomes `http://bluebirdjs.com/bluebird/web/docs/deprecated_apis.html`
=> Fix deprecated APIs URL

docs/docs/coming-from-other-libraries.md
The example doesn't work because `Promise.delay` takes `ms` milliseconds as the first argument.
This small change makes the example work again.
=> [Docs] Fix order of arguments passed to Promise.delay

docs/docs/api/promise.coroutine.addyieldhandler.md, docs/docs/api/promise.coroutine.md
This PR adds documentation for `Promise.coroutine()` `yieldHandler` option.
It also simplifies one of the other code examples for `Promise.coroutine.addYieldHandler()`.
=> Add documentation of `Promise.coroutine()` `yieldHandler` option

docs/docs/api/promise.resolve.md
Based this on the Promise.method. Not sure if that was a special case.
Also, not sure of my jQuery example description. It probably needs a clearer description in any case.
Is it just casting a jQuery then-able not-quite-promise to a Bluebird promise?
Special for jQuery or is this for any then-able object, say from another Promise library?
=> promise.resolve.md - static->promise example

docs/docs/api/promise.props.md
The second example for Promise.props has a bug in how it uses lodash. It needs `_.chain()` to work, not just `_()`.
PR for #1189
=> Small correction to Promise.props example

.gitignore, src/debuggability.js, test/browser/promise_debug.js, test/browser/worker.js, test/mocha/unhandled_rejections.js, tools/browser_test_generator.js
#1191 introduced two regressions:
1. It did not pass properly the details of the event. This was fixed in commit 288aa285fe61d4a9c360253eb5cbb66d04a81c62.
2. It did not make the event cancelable. This PR fixes this.
It also overlooked a problem with Firefox versions earlier than 48. Those versions do not make `CustomEvent` available in workers. It is a bug in Firefox but it is going to bite users of Bluebird unless Bluebird takes action to work around it. The current ESR of Firefox is version 45, which has the bug.
I've also added a test that summarily checks that events raised in workers can be caught with global handlers. Right now I have both `node tools/test`, and `node tools/test --browser` with Firefox pass all tests. 
Unfortunately, the browser tests do not pass on Chrome 51 but …
=> Fixes a regression introduced by #1191 and a problem it overlooked.

.travis.yml
This PR adds coverage for Node v6.x to Travis CI run.
=> Run Travis CI on Node v6

src/map.js, test/mocha/map.js
=> `.map` callback called async (closes #1148)

docs/docs/async-dialogs.md
Fix typo 'local' -> 'locale' in order to get JS working.
=> Fix base html sample for Async Dialog tutorial

tools/build.js
I have several bluebird repos in the same parent directory and I suffix them differently to distinguish them (e.g. `bluebird/` for petkaantonov/bluebird, and `bluebird-finnigantime/` for my fork of it). There is a check in build.js that prevents building/testing if the directory does not exactly match "bluebird". Here's a suggestion to relax that check to just check for "bluebird" at the beginning of the directory string, which I think still provides the same value while allowing multiple bluebird repos with different suffixes to coexist in the same parent directory.
Manually tested that the check still works:
=> relax directory check

src/debuggability.js
SyntaxErrors in node.js are different from other Errors in JS - the first 3 lines of the stack specify the file, lineno, and code snippet where the error occurred. Previously, longStackTraces were stripping this information, which made identifying the fix problematic. This diff keeps this info in the stack.
(was #1281)
=> Fix for #1280 - Don't drop SyntaxError context for longStackTraces

src/schedule.js
I assume bad indentation was not intentional, the indentation under the `if (toggleScheduled)` made the code rather confusing :)
=> Fix bad indentation in mutation observer scheduler

docs/docs/api/promise.coroutine.md
Some lines are missing semicolons. The other documentation examples seem to use it.
=> Add missing semicolons in promise.coroutine.md

docs/docs/api/return.md
Replaced the confusing use of the legacy .thenReturn() in the last code example with the expected .return() instead.
=> Fixed confusing use of thenReturn in code example

test/mocha/cancel.js
Adding some regression tests around isCancelled(). These tests are green against bluebird master:
In our fork of bluebird, we moved over from bluebird2 to bluebird3 a few months ago so we're on a slightly older version of bluebird still. We have some issues with this version around cancellation, and the second unit test here isolates one of these issues - it fails in our fork:
Looks like we can merge the latest release of bluebird to fix the issue on our side. Adding these tests to protect this behavior.
=> add isCancelled() regression tests

src/generators.js, test/mocha/generator.js
When rejecting a non-promise value, string.replace is used, and the value is passed as second parameter. But string.replace, if the second parameter is a function, will call that function.
This commit fixes this by using value.toString().
=> Fixed #1314:  yielding a function should not call the function

src/promise.js
If `.catch` is passed a non-object instead of a predicate, I found the current error message a bit difficult to read:
> TypeError: expecting an object but got A catch statement predicate [object String]
New error message: 
> TypeError: Catch statement predicate: expecting an object but got [object String]
(Sorry if you don't like these sort of "trivial" pull requests)
=> Reword the catch predicate TypeError message for clarity

docs/docs/api/tap.md
As shown in this [example](https://runkit.com/58a6215425e6da0013370a71/58a6215425e6da0013370a72/branches/master) `.tap` is not called when there is a rejection. This fixes the text to correctly represent that in the docs.
=> Fix typo which mentioned that tap was called for rejections.

package.json
I'm using Bluebird 3.4.7 with webpack 1 and noticed it was clobbering the global variable `P`. I could see the snippet at the end of the script that it puts itself in the global namespace.
```js
;if (typeof window !== 'undefined' && window !== null) {
window.P = window.Promise;
} else if (typeof self !== 'undefined' && self !== null) {
self.P = self.Promise;
}
```
I investigated a bit and found out that webpack will use the "browser" field from package.json if it's available. From [the webpack docs](http://webpack.github.io/docs/configuration.html#resolve-packagemains):
> Check these fields in the package.json for suitable files.
> Default: ["webpack", "browser", "web", "browserify", ["jam", "main"], "main"]
This means that webpack picks the "browser" version instead of "main". Running …
=> Added dedicated webpack entry point.

docs/docs/api-reference.md
Actual documentation lives at `api/tapcatch.html`, not `api/tapCatch.html`.
=> Fix link to tapCatch documentation

docs/docs/api/all.md
the existing docs are unclear about the method consuming the value from the previous promise.
feel free to correct me if its doesn't match the docs style and phrasing
=> improve .all() docs

src/debuggability.js, test/mocha/unhandled_rejections.js
=> Conform to spec when generating PromiseRejectionEvent

docs/docs/api-reference.md
The current link from the API ref goes to `.delay`, but that page refers to `Promise.delay`. This will add a direct link to the already existing page.
=> Add direct link to Promise.delay from API ref

docs/docs/new-in-bluebird-3.md
I can't be sure what the intended meaning was:
...the same as the new...
or 
...close to the same as the new...
=> Fix a doc typo.

.travis.yml, package.json, src/async.js, src/debuggability.js, src/promise.js, test/mocha/async.js
Achieved by draining each queue element in a separate function.
Resolves https://github.com/petkaantonov/bluebird/issues/1529. The issue provides a way to easily reproduce this issue.
I'm currently looking into adding a test to assert this behaviour.
=> Fix memory being retained until promise queue is completely empty

docs/docs/getting-started.md
There need to be line breaks before the embedded code snippet for "Alternatively in ES6". 
If there are no line breaks, then the programming language (`js`) used for the syntax highlighting will be rendered as part of the sentence in the docs:
**Bug**
You can see the problem here: http://bluebirdjs.com/docs/getting-started.html
=> Fix embedded code snippet

.gitignore, docs/_layouts/default.html
Currently this is 404ing on the live docs
Updated to be the same as suggested on the [install](http://bluebirdjs.com/docs/install.html) page
=> Update jsdelivr url in docs

docs/docs/coming-from-other-languages.md
Titles were lacking spaces, breaking linking from the ToC and making it hard to read.
=> .md syntax fix for coming-from-other-languages.md

docs/docs/api/promise.each.md, docs/docs/api/promise.mapseries.md
From [the docs for `Promise.each`](http://bluebirdjs.com/docs/api/promise.each.html):
> This article is partially or completely unfinished. You are welcome to create pull requests to help completing this article. 
This pull request is a rewrite of the documentation of `Promise.each`, making it complete (I believe).
Also, `Promise.mapSeries` is very similar to `Promise.each` (the former was born in #821 based on `Promise.each`), so I thought that the documentations of both functions should be more closely related. This way, this pull request also rewrites the documentation of `Promise.mapSeries`, yielding two similar documentations that clarify the difference between both functions.
Not only rewriting the text, I also changed the examples to ones that I believe to be clearer and more …
=> docs: improve and compare Promise.each and Promise.mapSeries

docs/docs/install.md
"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358
=> Remove --save option as it isn't required anymore

src/promise.js
Fixes #1277.
Doesn't come with tests (yet?) - would you like me to add them, and if so where?
=> Added Symbol.toStringTag support to Promise

docs/docs/getting-started.md
Using the old import strategy, the following error is produced:
```js
Uncaught TypeError: Promise is not a constructor
```
It's been fixed in this PR.
=> Fix ES6 import strategy

src/call_get.js, src/errors.js, src/nodeify.js, src/timers.js, src/util.js, test/browser/main.js, test/mocha/bind.js, test/mocha/helpers/assert_long_trace.js, tools/ast_passes.js, tools/browser_test_generator.js, tools/browser_test_runner.js, tools/mocha_runner.js, tools/saucelabs_runner.js, tools/test.js, tools/utils.js
Tests are still passing. Let me know if I can adjust anything.
The commits are fine-grained because they are generated automatically. Feel free to squash them on merge.
=> Making type conversions explicit

benchmark/madeup-parallel/generators-tj-co.js
Since I wanted to execute parallel benchmark of bluebird and co generator in Node-v 6.x, added co generator benchmark to Madeup parallel.
=> Add a co generator benchmark for Madeup parallel

test/browser/es5-shim.js
There is a small typo in test/browser/es5-shim.js.
Should read `standard` rather than `standart`.
=> docs: Fix simple typo, standart -> standard
