petkaantonov/bluebird

README.md

Reverts petkaantonov/bluebird#440

Revert "Readme: fix line-through on github"

---

API.md

Fix typo in .settle docs

---

API.md

Fix typo in API.md

---

docs/docs/what-about-generators.md

Last one was merged to fast. Please review if you have further feedback, then merge :smile:

Feedback on last PR

---

API.md

Small change to correct formatting of one line.

Correct Markdown Syntax

---

docs/docs/deprecated_apis.md

I included a reference to [deferred anti-pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern) page as well.

Few minor grammar and formatting changes

---

API.md

fix errant whitespace closing fenced code block in API.md

---

docs/docs/api/reflect.md

Fix missing word in reflect.md

---

docs/docs/api/delay.md
docs/docs/api/promise.delay.md

https://github.com/petkaantonov/bluebird/commit/26b6a20777d4cb8f5ad3db4d4f9ca8a9dd3f9e6a swapped argument positions.

docs(promise.delay): fix changed signature

---

src/timers.js
test/mocha/timers.js

Not sure if this is the right "fix", but the behaviour is now a bit more similar to bluebird 2's timeout as described in #891
However this may be considered a breaking change...

Ensure timeout cancels parent (fixes #891)

---

docs/docs/coming-from-other-libraries.md

The documentation here conflicted with the documentation on [this page](http://bluebirdjs.com/docs/api/promise.each.html) as well as the actual functionality of the `Promise.each` method.

Fixes example for replicating async.series with Promise.each

---

docs/docs/api/disposer.md

Not sure if I should also make all Promise.using references links...

Backport disposer docs and a few other enhancements

---

docs/docs/error-explanations.md

Updated the help page to reflect recent (Dec, 2015) changes to the bluebird wiki.

Update "Error: expecting an array or Promise"

---

docs/docs/api/promise.setscheduler.md

The implementation returns the previous scheduler.

Change documentation according to implementation

---

docs/docs/error-explanations.md

The code block was not syntax highlighted.

Fix code formatting

---

docs/docs/api/spread.md

Update !== to (apparently) intended ===

---

test/mocha/map.js

There was test description and test method mismatch in `tests/mocha/map.js`

fixed wrong test description

---

docs/docs/api/catch.md

rename parma to param

---

src/generators.js
test/mocha/generator.js

Ensure Promise.coroutine always handles yielded Promises asynchronously

---

src/debuggability.js

Add link to unhandled warning docs

---

docs/docs/async-dialogs.md

This is an attempt to show Bluebird and Promises when used as values from a dialog box. I use only Bluebird as a dependency and the DOM code is vanilla JS not jQuery.
I first compare the `window.confirm` synchronous code with a asynchronous dialog written in the DOM. Then I refactor the example to a few OOP abstractions which allow be to demonstrate different types of dialogs like a prompt.
I follow this with an explanation on how to best handle the cancellation of the dialog box using custom Errors.
And finally I offer and example on how to provide progress updates by using a progress bar dialog.

Add a first draft of an Async Dialog Tutorial

---

docs/docs/features.md
docs/docs/install.md
docs/docs/warning-explanations.md

Mention warning flag. Closes #1181

Mention warning flag

---

docs/docs/features.md

Hey @benjamingr @spion @petkaantonov and anyone else interested in docs.
I was hoping to add more examples and/or do write ups on the blank pages (i.e. tutorials).
Is there anything in particular you are looking for? (Should a tutorial be something like "HowTo: 'Promise' a Twitter Bootstrap's Dialog" or "HowTo: Replace $q with Bluebird in Angular"? )
Anyway, looking forward to your feedback on this PR. 
Thx!

Add Timeout & Cancellation Example to `features.md`

---

src/each.js
src/map.js
src/reduce.js

Don't allocate an additional array in Promise.each

---

docs/docs/api/promise.config.md
src/debuggability.js

Added 'Bluebird library' return value to Promise.config

---

src/async.js
src/queue.js
test/mocha/using.js
tools/job-runner/job-runner.js
tools/mocha_runner.js
tools/utils.js

After reading #1243 I looked in the code and I could not find any call to the mentioned function. Therefore I guess it's dead code and safe to remove. I also looked a bit further and stumbled across some more dead code and some missing `var` statements.
Fixes #1243

Remove dead code

---

src/util.js

https://github.com/petkaantonov/bluebird/issues/1294

Fix getting env variables

---

docs/docs/async-dialogs.md

Nothing too interesting here, just some discovered typos.

Correct a few found typos in async-dialogs.md

---

src/schedule.js

The indentation didn't match the control flow.

Fix misleading indentation

---

docs/docs/api/promise.coroutine.md

Added some missing semicolon to the javascript code

Formated the javascript code example

---

docs/docs/api-reference.md
docs/docs/api/tapcatch.md
src/finally.js
test/mocha/tapCatch.js

Fixes to tapError implementation/tests

---

docs/docs/error-explanations.md

fixes markdown headers

---

docs/docs/api/tap.md

This might not be perfect, but it's better than what's there. :)

Update doco for  tap()

---

tools/README.md

Should leave space between sharp sign and title.

Fix title style

---

src/util.js

See https://github.com/petkaantonov/bluebird/issues/990#issuecomment-333598787

Better error check

---

docs/docs/getting-started.md

Added ES6 way to import the bluebird promise

Added ES6 / babel way to import the bluebird promise

---

README.md

Pretty simple, just fixed a typo I noticed when reading the doco.

Fix typo in readme introduced in #1530

---

docs/docs/api/promise.each.md

Fix for formatting and spelling. One example on the webpage is quite unreadable as the formatting is broken, this adjustment should make it readable again.

Update promise.each.md to fix formatting and spelling

---

src/util.js

added a version check for the `process`.
This adds support for the debugger running inside VSCode.

added proper version check supporting VSCode

---

docs/docs/contribute.md

missing ` --expose-gc ` flag

---

src/util.js

Reuse classString function

---

.jshintrc
src/debuggability.js
src/join.js
src/map.js
src/promise.js
src/reduce.js
src/util.js
test/mocha/async_hooks.js
tools/ast_passes.js
tools/build.js
tools/jshintrc_generator.js

See https://github.com/petkaantonov/bluebird/pull/1472

Optimize async hooks
